version: "3"
services:

  kafka-connect-ui:
    container_name: kafka-connect-ui
    image: landoop/kafka-connect-ui
    environment:
      CONNECT_URL: http://debezium:8083
    networks:
      - default
    depends_on:
      - debezium
      - schema-registry
      - kafka
      - zookeeper
    ports:
    - 8000:8000

  debezium:
    container_name: debezium
    image: debezium/connect:1.2
    user: root
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      HOST_NAME: debezium
      REST_PORT: 8083
      REST_HOST_NAME: debezium
      ADVERTISED_PORT: 8083
      ADVERTISED_HOST_NAME: debezium
      BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - default
    depends_on:
      - schema-registry
      - kafka
      - zookeeper
    ports:
    - 8083:8083
    - 80:80

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME : schema-registry
      SCHEMA_REGISTRY_LISTENERS : http://schema-registry:8081
    networks:
      - default
    depends_on:
      - kafka
      - zookeeper
    ports:
    - 8181:8181
    - 8081:8081


  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "my_connect_configs:1:1, my_connect_offsets:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - default
    depends_on:
      - zookeeper
    ports:
      - 9094:9094

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    networks:
      - default
    ports:
      - 2181:2181


networks:
  default:
    external:
      name: debezium-net
